### ISSUE TITLE
mvp+/v1 tracking

### ISSUE THREAD

**Issue by philbarker** [philbarker/OCXChecker#12]
Must be done for v1:
- [ ] #9 Write tests (mostly done, not big job)
- [ ] #6 rename & set up w/o ref to OCX (not big job)
- [ ] #3 configurability (big job, needs breaking down)
- [ ] #2 input form for web (not big job)
- [ ] #4 better formatted results (medium job)
- [ ] #5 info and about pages (not big job)

should be done:
- [ ] #8 API (not too big a job)
- [ ] #7 cmd line (see what's in place after testing)

could be done
- [ ] #10 input by file upload
- [ ] #11 input by test field
