### ISSUE TITLE
UI: Input Form for web

### ISSUE THREAD

**Issue by philbarker** [philbarker/OCXChecker#2]
Need a simple input form, probably with options for loading data by 
- [ ] URL, 
- [ ] file upload, 
- [ ] text entry.
Also options for
- [ ] verbose / terse output 
- [ ] showing input data in ttl
- [ ] showing input data in JSON
