### ISSUE TITLE
Configurability

### ISSUE THREAD

**Issue by philbarker** [philbarker/OCXChecker#3]
Ability to specify which checks are run.
- [ ] allow RDFS source of specs to be chosen (probably part of setting up an instance)

Use a config file to specify checks such as:
- [ ] cardinality of entities (which resource types must be present)
- [ ] cardinality of properties per entity type (which properties/predicates must be present)
- [ ] restrict allowed range of property
- [ ] specify value set that must be used for property

This requires:
- [ ] checks to be relatively generic, e.g. have ~3 types of check (entity, predicate-range & predicate-domain, as now) but not hard wire what get checked.
