### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by philbarker** [philbarker/OCXChecker#9]
Need unit tests for what is already there in:
- [x] pagedata.py
- [x] ocxgraph.py
- [x] schemagraph.py
- [x] checkutils.py
- [x] datachecks.py
- [x] reports.py

Also need tests for
- [x] integration tests 
- [x] code style (blacking)
- [x] installation tests

And need regular testing framework
- [x] set up travis.ci
- [x] set up codecov

**Comment by philbarker** [comment]
Integration tests added with commit dc93eb002

**Comment by philbarker** [comment]
blacking is tested by pre-commit by 00a9a944f467f89d287b85c70637c556e611b1cf

travis CI set up & running by 2c9f8ebb7486be21009668a504dfae788813a8ea  which also involves installation test

code cov set up & runing by 81ee0108c5e7f679f3431e297ab4691e198b55bf
